// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Notice documents */
interface NoticeDocumentData {
    /**
     * Title field in *Notice*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: notice.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Banner field in *Notice*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: notice.banner
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    banner: prismicT.ImageField<never>;
    /**
     * Subtitle field in *Notice*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: notice.subtitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * First_Field_Article field in *Notice*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: notice.first_field_article
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    first_field_article: prismicT.RichTextField;
    /**
     * Image_Information field in *Notice*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: notice.image_information
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_information: prismicT.ImageField<never>;
    /**
     * Second_Field_Article field in *Notice*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: notice.second_field_article
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    second_field_article: prismicT.RichTextField;
}
/**
 * Notice document from Prismic
 *
 * - **API ID**: `notice`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NoticeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<NoticeDocumentData>, "notice", Lang>;
export type AllDocumentTypes = NoticeDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { NoticeDocumentData, NoticeDocument, AllDocumentTypes };
    }
}
